jobs:
  run:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Download Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./test/run

name: Build

on:
  schedule:
    - cron: "0 */3 * * *"
